spring:
   cloud:
      config:
         server:
            git:
               uri: https://github.com/kravisingh2/ms-config
   application:
    name: CONFIG-SERVER 
                
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761
  instance:
    hostname: localhost
    
server:
  port: 9595
     